// Code generated by arcjet-gravity; DO NOT EDIT.

package classifier

import (
	"context"
	"errors"

	"github.com/tetratelabs/wazero"
	"github.com/tetratelabs/wazero/api"

	_ "embed"
)

type IClassifierHttp interface{}

type HttpVersion struct {
	Major uint32
	Minor uint32
}

type OsInfo struct {
	FullName string
	Name     string
	Version  string
}

type Version struct {
	Name    string
	Version string
}

type UserAgent struct {
	Bot          bool
	Browser      Version
	Engine       Version
	Localization string
	Mobile       bool
	Model        string
	Os           string
	OsInfo       OsInfo
	Platform     string
	Orig         string
}

type SecChUa struct {
	Versions []Version
	Mobile   *bool
	Platform string
	Arch     string
	Bitness  string
}

type HttpRequest struct {
	Method    string
	Path      string
	Query     string
	Proto     HttpVersion
	UserAgent UserAgent
	SecChUa   *SecChUa
}

type MobileLikelihood struct {
	IsSlow  bool
	IsPhone bool
	IsBot   bool
}

type ClassifierFactory struct {
	runtime wazero.Runtime
	module  wazero.CompiledModule
}

func NewPhoneClassifierFactory(
	ctx context.Context,
	wasmFilePhoneClassifier []byte,
) (*ClassifierFactory, error) {
	wazeroRuntime := wazero.NewRuntime(ctx)

	_, err0 := wazeroRuntime.NewHostModuleBuilder("techaro:http/http").
		Instantiate(ctx)
	if err0 != nil {
		return nil, err0
	}

	// Compiling the module takes a LONG time, so we want to do it once and hold
	// onto it with the Runtime
	module, err := wazeroRuntime.CompileModule(ctx, wasmFilePhoneClassifier)
	if err != nil {
		return nil, err
	}
	return &ClassifierFactory{
		runtime: wazeroRuntime,
		module:  module,
	}, nil
}

func (f *ClassifierFactory) Instantiate(ctx context.Context) (*ClassifierInstance, error) {
	if module, err := f.runtime.InstantiateModule(ctx, f.module, wazero.NewModuleConfig()); err != nil {
		return nil, err
	} else {
		return &ClassifierInstance{module}, nil
	}
}

func (f *ClassifierFactory) Close(ctx context.Context) {
	f.runtime.Close(ctx)
}

type ClassifierInstance struct {
	module api.Module
}

func (i *ClassifierInstance) Close(ctx context.Context) error {
	if err := i.module.Close(ctx); err != nil {
		return err
	}

	return nil
}

// writeString will put a Go string into the Wasm memory following the Component
// Model calling conventions, such as allocating memory with the realloc function
func writeString(
	ctx context.Context,
	s string,
	memory api.Memory,
	realloc api.Function,
) (uint64, uint64, error) {
	if len(s) == 0 {
		return 1, 0, nil
	}

	results, err := realloc.Call(ctx, 0, 0, 1, uint64(len(s)))
	if err != nil {
		return 1, 0, err
	}
	ptr := results[0]
	ok := memory.Write(uint32(ptr), []byte(s))
	if !ok {
		return 1, 0, errors.New("failed to write string to wasm memory")
	}
	return uint64(ptr), uint64(len(s)), nil
}

func (i *ClassifierInstance) IsMobile(
	ctx context.Context,
	req HttpRequest,
) (MobileLikelihood, error) {
	arg0 := req
	// Allocate the area holding the indirectly passed parameters
	result0, err0 := i.module.ExportedFunction("cabi_realloc").Call(ctx, 0, 0, 4, 176)
	if err0 != nil {
		var default0 MobileLikelihood
		return default0, err0
	}
	ptr0 := uint32(result0[0])
	method1 := arg0.Method
	path1 := arg0.Path
	query1 := arg0.Query
	proto1 := arg0.Proto
	userAgent1 := arg0.UserAgent
	secChUa1 := arg0.SecChUa
	memory2 := i.module.Memory()
	realloc2 := i.module.ExportedFunction("cabi_realloc")
	ptr2, len2, err2 := writeString(ctx, method1, memory2, realloc2)
	if err2 != nil {
		var default2 MobileLikelihood
		return default2, err2
	}
	i.module.Memory().WriteUint32Le(ptr0+4, uint32(len2))
	i.module.Memory().WriteUint32Le(ptr0+0, uint32(ptr2))
	memory3 := i.module.Memory()
	realloc3 := i.module.ExportedFunction("cabi_realloc")
	ptr3, len3, err3 := writeString(ctx, path1, memory3, realloc3)
	if err3 != nil {
		var default3 MobileLikelihood
		return default3, err3
	}
	i.module.Memory().WriteUint32Le(ptr0+12, uint32(len3))
	i.module.Memory().WriteUint32Le(ptr0+8, uint32(ptr3))
	memory4 := i.module.Memory()
	realloc4 := i.module.ExportedFunction("cabi_realloc")
	ptr4, len4, err4 := writeString(ctx, query1, memory4, realloc4)
	if err4 != nil {
		var default4 MobileLikelihood
		return default4, err4
	}
	i.module.Memory().WriteUint32Le(ptr0+20, uint32(len4))
	i.module.Memory().WriteUint32Le(ptr0+16, uint32(ptr4))
	major5 := proto1.Major
	minor5 := proto1.Minor
	result6 := uint32(major5)
	i.module.Memory().WriteUint32Le(ptr0+24, result6)
	result7 := uint32(minor5)
	i.module.Memory().WriteUint32Le(ptr0+28, result7)
	bot8 := userAgent1.Bot
	browser8 := userAgent1.Browser
	engine8 := userAgent1.Engine
	localization8 := userAgent1.Localization
	mobile8 := userAgent1.Mobile
	model8 := userAgent1.Model
	os8 := userAgent1.Os
	osInfo8 := userAgent1.OsInfo
	platform8 := userAgent1.Platform
	orig8 := userAgent1.Orig
	var value9 uint32
	if bot8 {
		value9 = 1
	} else {
		value9 = 0
	}
	var byte10 uint8
	switch value9 {
	case 0:
		byte10 = 0
	case 1:
		byte10 = 1
	default:
		// TODO(#8): Return an error if the return type allows it
		panic(errors.New("invalid int8 value encountered"))
	}
	i.module.Memory().WriteByte(ptr0+32, byte10)
	name11 := browser8.Name
	version11 := browser8.Version
	memory12 := i.module.Memory()
	realloc12 := i.module.ExportedFunction("cabi_realloc")
	ptr12, len12, err12 := writeString(ctx, name11, memory12, realloc12)
	if err12 != nil {
		var default12 MobileLikelihood
		return default12, err12
	}
	i.module.Memory().WriteUint32Le(ptr0+40, uint32(len12))
	i.module.Memory().WriteUint32Le(ptr0+36, uint32(ptr12))
	memory13 := i.module.Memory()
	realloc13 := i.module.ExportedFunction("cabi_realloc")
	ptr13, len13, err13 := writeString(ctx, version11, memory13, realloc13)
	if err13 != nil {
		var default13 MobileLikelihood
		return default13, err13
	}
	i.module.Memory().WriteUint32Le(ptr0+48, uint32(len13))
	i.module.Memory().WriteUint32Le(ptr0+44, uint32(ptr13))
	name14 := engine8.Name
	version14 := engine8.Version
	memory15 := i.module.Memory()
	realloc15 := i.module.ExportedFunction("cabi_realloc")
	ptr15, len15, err15 := writeString(ctx, name14, memory15, realloc15)
	if err15 != nil {
		var default15 MobileLikelihood
		return default15, err15
	}
	i.module.Memory().WriteUint32Le(ptr0+56, uint32(len15))
	i.module.Memory().WriteUint32Le(ptr0+52, uint32(ptr15))
	memory16 := i.module.Memory()
	realloc16 := i.module.ExportedFunction("cabi_realloc")
	ptr16, len16, err16 := writeString(ctx, version14, memory16, realloc16)
	if err16 != nil {
		var default16 MobileLikelihood
		return default16, err16
	}
	i.module.Memory().WriteUint32Le(ptr0+64, uint32(len16))
	i.module.Memory().WriteUint32Le(ptr0+60, uint32(ptr16))
	memory17 := i.module.Memory()
	realloc17 := i.module.ExportedFunction("cabi_realloc")
	ptr17, len17, err17 := writeString(ctx, localization8, memory17, realloc17)
	if err17 != nil {
		var default17 MobileLikelihood
		return default17, err17
	}
	i.module.Memory().WriteUint32Le(ptr0+72, uint32(len17))
	i.module.Memory().WriteUint32Le(ptr0+68, uint32(ptr17))
	var value18 uint32
	if mobile8 {
		value18 = 1
	} else {
		value18 = 0
	}
	var byte19 uint8
	switch value18 {
	case 0:
		byte19 = 0
	case 1:
		byte19 = 1
	default:
		// TODO(#8): Return an error if the return type allows it
		panic(errors.New("invalid int8 value encountered"))
	}
	i.module.Memory().WriteByte(ptr0+76, byte19)
	memory20 := i.module.Memory()
	realloc20 := i.module.ExportedFunction("cabi_realloc")
	ptr20, len20, err20 := writeString(ctx, model8, memory20, realloc20)
	if err20 != nil {
		var default20 MobileLikelihood
		return default20, err20
	}
	i.module.Memory().WriteUint32Le(ptr0+84, uint32(len20))
	i.module.Memory().WriteUint32Le(ptr0+80, uint32(ptr20))
	memory21 := i.module.Memory()
	realloc21 := i.module.ExportedFunction("cabi_realloc")
	ptr21, len21, err21 := writeString(ctx, os8, memory21, realloc21)
	if err21 != nil {
		var default21 MobileLikelihood
		return default21, err21
	}
	i.module.Memory().WriteUint32Le(ptr0+92, uint32(len21))
	i.module.Memory().WriteUint32Le(ptr0+88, uint32(ptr21))
	fullName22 := osInfo8.FullName
	name22 := osInfo8.Name
	version22 := osInfo8.Version
	memory23 := i.module.Memory()
	realloc23 := i.module.ExportedFunction("cabi_realloc")
	ptr23, len23, err23 := writeString(ctx, fullName22, memory23, realloc23)
	if err23 != nil {
		var default23 MobileLikelihood
		return default23, err23
	}
	i.module.Memory().WriteUint32Le(ptr0+100, uint32(len23))
	i.module.Memory().WriteUint32Le(ptr0+96, uint32(ptr23))
	memory24 := i.module.Memory()
	realloc24 := i.module.ExportedFunction("cabi_realloc")
	ptr24, len24, err24 := writeString(ctx, name22, memory24, realloc24)
	if err24 != nil {
		var default24 MobileLikelihood
		return default24, err24
	}
	i.module.Memory().WriteUint32Le(ptr0+108, uint32(len24))
	i.module.Memory().WriteUint32Le(ptr0+104, uint32(ptr24))
	memory25 := i.module.Memory()
	realloc25 := i.module.ExportedFunction("cabi_realloc")
	ptr25, len25, err25 := writeString(ctx, version22, memory25, realloc25)
	if err25 != nil {
		var default25 MobileLikelihood
		return default25, err25
	}
	i.module.Memory().WriteUint32Le(ptr0+116, uint32(len25))
	i.module.Memory().WriteUint32Le(ptr0+112, uint32(ptr25))
	memory26 := i.module.Memory()
	realloc26 := i.module.ExportedFunction("cabi_realloc")
	ptr26, len26, err26 := writeString(ctx, platform8, memory26, realloc26)
	if err26 != nil {
		var default26 MobileLikelihood
		return default26, err26
	}
	i.module.Memory().WriteUint32Le(ptr0+124, uint32(len26))
	i.module.Memory().WriteUint32Le(ptr0+120, uint32(ptr26))
	memory27 := i.module.Memory()
	realloc27 := i.module.ExportedFunction("cabi_realloc")
	ptr27, len27, err27 := writeString(ctx, orig8, memory27, realloc27)
	if err27 != nil {
		var default27 MobileLikelihood
		return default27, err27
	}
	i.module.Memory().WriteUint32Le(ptr0+132, uint32(len27))
	i.module.Memory().WriteUint32Le(ptr0+128, uint32(ptr27))
	if secChUa1 == nil {
		i.module.Memory().WriteByte(ptr0+136, 0)
	} else {
		variantPayload := *secChUa1
		i.module.Memory().WriteByte(ptr0+136, 1)
		versions28 := variantPayload.Versions
		mobile28 := variantPayload.Mobile
		platform28 := variantPayload.Platform
		arch28 := variantPayload.Arch
		bitness28 := variantPayload.Bitness
		vec32 := versions28
		len32 := uint64(len(vec32))
		result32, err32 := i.module.ExportedFunction("cabi_realloc").Call(ctx, 0, 0, 4, len32*16)
		if err32 != nil {
			var default32 MobileLikelihood
			return default32, err32
		}
		ptr32 := result32[0]
		for idx := uint64(0); idx < len32; idx++ {
			e := vec32[idx]
			base := uint32(ptr32 + uint64(idx)*uint64(16))
			name29 := e.Name
			version29 := e.Version
			memory30 := i.module.Memory()
			realloc30 := i.module.ExportedFunction("cabi_realloc")
			ptr30, len30, err30 := writeString(ctx, name29, memory30, realloc30)
			if err30 != nil {
				var default30 MobileLikelihood
				return default30, err30
			}
			i.module.Memory().WriteUint32Le(base+4, uint32(len30))
			i.module.Memory().WriteUint32Le(base+0, uint32(ptr30))
			memory31 := i.module.Memory()
			realloc31 := i.module.ExportedFunction("cabi_realloc")
			ptr31, len31, err31 := writeString(ctx, version29, memory31, realloc31)
			if err31 != nil {
				var default31 MobileLikelihood
				return default31, err31
			}
			i.module.Memory().WriteUint32Le(base+12, uint32(len31))
			i.module.Memory().WriteUint32Le(base+8, uint32(ptr31))
		}
		i.module.Memory().WriteUint32Le(ptr0+144, uint32(len32))
		i.module.Memory().WriteUint32Le(ptr0+140, uint32(ptr32))
		if mobile28 == nil {
			i.module.Memory().WriteByte(ptr0+148, 0)
		} else {
			variantPayload := *mobile28
			i.module.Memory().WriteByte(ptr0+148, 1)
			var value33 uint32
			if variantPayload {
				value33 = 1
			} else {
				value33 = 0
			}
			var byte34 uint8
			switch value33 {
			case 0:
				byte34 = 0
			case 1:
				byte34 = 1
			default:
				// TODO(#8): Return an error if the return type allows it
				panic(errors.New("invalid int8 value encountered"))
			}
			i.module.Memory().WriteByte(ptr0+149, byte34)
		}
		memory36 := i.module.Memory()
		realloc36 := i.module.ExportedFunction("cabi_realloc")
		ptr36, len36, err36 := writeString(ctx, platform28, memory36, realloc36)
		if err36 != nil {
			var default36 MobileLikelihood
			return default36, err36
		}
		i.module.Memory().WriteUint32Le(ptr0+156, uint32(len36))
		i.module.Memory().WriteUint32Le(ptr0+152, uint32(ptr36))
		memory37 := i.module.Memory()
		realloc37 := i.module.ExportedFunction("cabi_realloc")
		ptr37, len37, err37 := writeString(ctx, arch28, memory37, realloc37)
		if err37 != nil {
			var default37 MobileLikelihood
			return default37, err37
		}
		i.module.Memory().WriteUint32Le(ptr0+164, uint32(len37))
		i.module.Memory().WriteUint32Le(ptr0+160, uint32(ptr37))
		memory38 := i.module.Memory()
		realloc38 := i.module.ExportedFunction("cabi_realloc")
		ptr38, len38, err38 := writeString(ctx, bitness28, memory38, realloc38)
		if err38 != nil {
			var default38 MobileLikelihood
			return default38, err38
		}
		i.module.Memory().WriteUint32Le(ptr0+172, uint32(len38))
		i.module.Memory().WriteUint32Le(ptr0+168, uint32(ptr38))
	}
	raw40, err40 := i.module.ExportedFunction("is-mobile").Call(ctx, uint64(ptr0))
	if err40 != nil {
		var default40 MobileLikelihood
		return default40, err40
	}

	// The cleanup via `cabi_post_*` cleans up the memory in the guest. By
	// deferring this, we ensure that no memory is corrupted before the function
	// is done accessing it.
	defer func() {
		if postFn := i.module.ExportedFunction("cabi_post_is-mobile"); postFn != nil {
			if _, err := postFn.Call(ctx, raw40...); err != nil {
				// If we get an error during cleanup, something really bad is
				// going on, so we panic. Also, you can't return the error from
				// the `defer`
				panic(errors.New("failed to cleanup"))
			}
		}
	}()

	results40 := raw40[0]
	value41, ok41 := i.module.Memory().ReadByte(uint32(results40 + 0))
	if !ok41 {
		var default41 MobileLikelihood
		return default41, errors.New("failed to read byte from memory")
	}
	var value52 MobileLikelihood
	var err52 error
	switch value41 {
	case 0:
		value42, ok42 := i.module.Memory().ReadByte(uint32(results40 + 4))
		if !ok42 {
			var default42 MobileLikelihood
			return default42, errors.New("failed to read byte from memory")
		}
		value43 := value42 != 0
		value44, ok44 := i.module.Memory().ReadByte(uint32(results40 + 5))
		if !ok44 {
			var default44 MobileLikelihood
			return default44, errors.New("failed to read byte from memory")
		}
		value45 := value44 != 0
		value46, ok46 := i.module.Memory().ReadByte(uint32(results40 + 6))
		if !ok46 {
			var default46 MobileLikelihood
			return default46, errors.New("failed to read byte from memory")
		}
		value47 := value46 != 0
		value48 := MobileLikelihood{
			IsSlow:  value43,
			IsPhone: value45,
			IsBot:   value47,
		}
		value52 = value48
	case 1:
		ptr49, ok49 := i.module.Memory().ReadUint32Le(uint32(results40 + 4))
		if !ok49 {
			var default49 MobileLikelihood
			return default49, errors.New("failed to read pointer from memory")
		}
		len50, ok50 := i.module.Memory().ReadUint32Le(uint32(results40 + 8))
		if !ok50 {
			var default50 MobileLikelihood
			return default50, errors.New("failed to read length from memory")
		}
		buf51, ok51 := i.module.Memory().Read(ptr49, len50)
		if !ok51 {
			var default51 MobileLikelihood
			return default51, errors.New("failed to read bytes from memory")
		}
		str51 := string(buf51)
		err52 = errors.New(str51)
	default:
		err52 = errors.New("invalid variant discriminant for expected")
	}
	return value52, err52
}
