// Code generated by arcjet-gravity; DO NOT EDIT.

package phone_classifier

import (
	"context"
	"errors"

	"github.com/tetratelabs/wazero"
	"github.com/tetratelabs/wazero/api"

	_ "embed"
)

type IPhoneClassifierHttp interface{}

type HttpVersion struct {
	Major uint8
	Minor uint8
}

type OsInfo struct {
	FullName string
	Name     string
	Version  string
}

type Version struct {
	Name    string
	Version string
}

type UserAgent struct {
	Bot          bool
	Browser      Version
	Engine       Version
	Localization string
	Mobile       bool
	Model        string
	Os           string
	OsInfo       OsInfo
	Platform     string
	Orig         string
}

type SecChUa struct {
	Versions []Version
	Mobile   *bool
	Platform string
	Arch     string
	Bitness  string
}

type HttpRequest struct {
	Method    string
	Path      string
	Query     string
	Proto     HttpVersion
	UserAgent UserAgent
	SecChUa   *SecChUa
}

type MobileLikelihood struct {
	IsSlow  bool
	IsPhone bool
	IsBot   bool
}

type PhoneClassifierFactory struct {
	runtime wazero.Runtime
	module  wazero.CompiledModule
}

func NewPhoneClassifierFactory(
	ctx context.Context,
	http IPhoneClassifierHttp,
	wasmFilePhoneClassifier []byte,
) (*PhoneClassifierFactory, error) {
	wazeroRuntime := wazero.NewRuntime(ctx)

	_, err0 := wazeroRuntime.NewHostModuleBuilder("techaro:http/http").
		Instantiate(ctx)
	if err0 != nil {
		return nil, err0
	}

	// Compiling the module takes a LONG time, so we want to do it once and hold
	// onto it with the Runtime
	module, err := wazeroRuntime.CompileModule(ctx, wasmFilePhoneClassifier)
	if err != nil {
		return nil, err
	}
	return &PhoneClassifierFactory{
		runtime: wazeroRuntime,
		module:  module,
	}, nil
}

func (f *PhoneClassifierFactory) Instantiate(ctx context.Context) (*PhoneClassifierInstance, error) {
	if module, err := f.runtime.InstantiateModule(ctx, f.module, wazero.NewModuleConfig()); err != nil {
		return nil, err
	} else {
		return &PhoneClassifierInstance{module}, nil
	}
}

func (f *PhoneClassifierFactory) Close(ctx context.Context) {
	f.runtime.Close(ctx)
}

type PhoneClassifierInstance struct {
	module api.Module
}

func (i *PhoneClassifierInstance) Close(ctx context.Context) error {
	if err := i.module.Close(ctx); err != nil {
		return err
	}

	return nil
}

// writeString will put a Go string into the Wasm memory following the Component
// Model calling conventions, such as allocating memory with the realloc function
func writeString(
	ctx context.Context,
	s string,
	memory api.Memory,
	realloc api.Function,
) (uint64, uint64, error) {
	if len(s) == 0 {
		return 1, 0, nil
	}

	results, err := realloc.Call(ctx, 0, 0, 1, uint64(len(s)))
	if err != nil {
		return 1, 0, err
	}
	ptr := results[0]
	ok := memory.Write(uint32(ptr), []byte(s))
	if !ok {
		return 1, 0, errors.New("failed to write string to wasm memory")
	}
	return uint64(ptr), uint64(len(s)), nil
}

func (i *PhoneClassifierInstance) IsMobile(
	ctx context.Context,
	req HttpRequest,
) (MobileLikelihood, error) {
	arg0 := req
	// Allocate the area holding the indirectly passed parameters
	result0, err0 := i.module.ExportedFunction("cabi_realloc").Call(ctx, 0, 0, 4, 172)
	if err0 != nil {
		var default0 MobileLikelihood
		return default0, err0
	}
	ptr0 := uint32(result0[0])
	method1 := arg0.Method
	path1 := arg0.Path
	query1 := arg0.Query
	proto1 := arg0.Proto
	userAgent1 := arg0.UserAgent
	secChUa1 := arg0.SecChUa
	memory2 := i.module.Memory()
	realloc2 := i.module.ExportedFunction("cabi_realloc")
	ptr2, len2, err2 := writeString(ctx, method1, memory2, realloc2)
	if err2 != nil {
		var default2 MobileLikelihood
		return default2, err2
	}
	i.module.Memory().WriteUint32Le(ptr0+4, uint32(len2))
	i.module.Memory().WriteUint32Le(ptr0+0, uint32(ptr2))
	memory3 := i.module.Memory()
	realloc3 := i.module.ExportedFunction("cabi_realloc")
	ptr3, len3, err3 := writeString(ctx, path1, memory3, realloc3)
	if err3 != nil {
		var default3 MobileLikelihood
		return default3, err3
	}
	i.module.Memory().WriteUint32Le(ptr0+12, uint32(len3))
	i.module.Memory().WriteUint32Le(ptr0+8, uint32(ptr3))
	memory4 := i.module.Memory()
	realloc4 := i.module.ExportedFunction("cabi_realloc")
	ptr4, len4, err4 := writeString(ctx, query1, memory4, realloc4)
	if err4 != nil {
		var default4 MobileLikelihood
		return default4, err4
	}
	i.module.Memory().WriteUint32Le(ptr0+20, uint32(len4))
	i.module.Memory().WriteUint32Le(ptr0+16, uint32(ptr4))
	major5 := proto1.Major
	minor5 := proto1.Minor
	value6 := api.EncodeI32(int32(major5))
	var byte7 uint8
	switch value6 {
	case 0:
		byte7 = 0
	case 1:
		byte7 = 1
	default:
		// TODO(#8): Return an error if the return type allows it
		panic(errors.New("invalid int8 value encountered"))
	}
	i.module.Memory().WriteByte(ptr0+24, byte7)
	value8 := api.EncodeI32(int32(minor5))
	var byte9 uint8
	switch value8 {
	case 0:
		byte9 = 0
	case 1:
		byte9 = 1
	default:
		// TODO(#8): Return an error if the return type allows it
		panic(errors.New("invalid int8 value encountered"))
	}
	i.module.Memory().WriteByte(ptr0+25, byte9)
	bot10 := userAgent1.Bot
	browser10 := userAgent1.Browser
	engine10 := userAgent1.Engine
	localization10 := userAgent1.Localization
	mobile10 := userAgent1.Mobile
	model10 := userAgent1.Model
	os10 := userAgent1.Os
	osInfo10 := userAgent1.OsInfo
	platform10 := userAgent1.Platform
	orig10 := userAgent1.Orig
	var value11 uint32
	if bot10 {
		value11 = 1
	} else {
		value11 = 0
	}
	var byte12 uint8
	switch value11 {
	case 0:
		byte12 = 0
	case 1:
		byte12 = 1
	default:
		// TODO(#8): Return an error if the return type allows it
		panic(errors.New("invalid int8 value encountered"))
	}
	i.module.Memory().WriteByte(ptr0+28, byte12)
	name13 := browser10.Name
	version13 := browser10.Version
	memory14 := i.module.Memory()
	realloc14 := i.module.ExportedFunction("cabi_realloc")
	ptr14, len14, err14 := writeString(ctx, name13, memory14, realloc14)
	if err14 != nil {
		var default14 MobileLikelihood
		return default14, err14
	}
	i.module.Memory().WriteUint32Le(ptr0+36, uint32(len14))
	i.module.Memory().WriteUint32Le(ptr0+32, uint32(ptr14))
	memory15 := i.module.Memory()
	realloc15 := i.module.ExportedFunction("cabi_realloc")
	ptr15, len15, err15 := writeString(ctx, version13, memory15, realloc15)
	if err15 != nil {
		var default15 MobileLikelihood
		return default15, err15
	}
	i.module.Memory().WriteUint32Le(ptr0+44, uint32(len15))
	i.module.Memory().WriteUint32Le(ptr0+40, uint32(ptr15))
	name16 := engine10.Name
	version16 := engine10.Version
	memory17 := i.module.Memory()
	realloc17 := i.module.ExportedFunction("cabi_realloc")
	ptr17, len17, err17 := writeString(ctx, name16, memory17, realloc17)
	if err17 != nil {
		var default17 MobileLikelihood
		return default17, err17
	}
	i.module.Memory().WriteUint32Le(ptr0+52, uint32(len17))
	i.module.Memory().WriteUint32Le(ptr0+48, uint32(ptr17))
	memory18 := i.module.Memory()
	realloc18 := i.module.ExportedFunction("cabi_realloc")
	ptr18, len18, err18 := writeString(ctx, version16, memory18, realloc18)
	if err18 != nil {
		var default18 MobileLikelihood
		return default18, err18
	}
	i.module.Memory().WriteUint32Le(ptr0+60, uint32(len18))
	i.module.Memory().WriteUint32Le(ptr0+56, uint32(ptr18))
	memory19 := i.module.Memory()
	realloc19 := i.module.ExportedFunction("cabi_realloc")
	ptr19, len19, err19 := writeString(ctx, localization10, memory19, realloc19)
	if err19 != nil {
		var default19 MobileLikelihood
		return default19, err19
	}
	i.module.Memory().WriteUint32Le(ptr0+68, uint32(len19))
	i.module.Memory().WriteUint32Le(ptr0+64, uint32(ptr19))
	var value20 uint32
	if mobile10 {
		value20 = 1
	} else {
		value20 = 0
	}
	var byte21 uint8
	switch value20 {
	case 0:
		byte21 = 0
	case 1:
		byte21 = 1
	default:
		// TODO(#8): Return an error if the return type allows it
		panic(errors.New("invalid int8 value encountered"))
	}
	i.module.Memory().WriteByte(ptr0+72, byte21)
	memory22 := i.module.Memory()
	realloc22 := i.module.ExportedFunction("cabi_realloc")
	ptr22, len22, err22 := writeString(ctx, model10, memory22, realloc22)
	if err22 != nil {
		var default22 MobileLikelihood
		return default22, err22
	}
	i.module.Memory().WriteUint32Le(ptr0+80, uint32(len22))
	i.module.Memory().WriteUint32Le(ptr0+76, uint32(ptr22))
	memory23 := i.module.Memory()
	realloc23 := i.module.ExportedFunction("cabi_realloc")
	ptr23, len23, err23 := writeString(ctx, os10, memory23, realloc23)
	if err23 != nil {
		var default23 MobileLikelihood
		return default23, err23
	}
	i.module.Memory().WriteUint32Le(ptr0+88, uint32(len23))
	i.module.Memory().WriteUint32Le(ptr0+84, uint32(ptr23))
	fullName24 := osInfo10.FullName
	name24 := osInfo10.Name
	version24 := osInfo10.Version
	memory25 := i.module.Memory()
	realloc25 := i.module.ExportedFunction("cabi_realloc")
	ptr25, len25, err25 := writeString(ctx, fullName24, memory25, realloc25)
	if err25 != nil {
		var default25 MobileLikelihood
		return default25, err25
	}
	i.module.Memory().WriteUint32Le(ptr0+96, uint32(len25))
	i.module.Memory().WriteUint32Le(ptr0+92, uint32(ptr25))
	memory26 := i.module.Memory()
	realloc26 := i.module.ExportedFunction("cabi_realloc")
	ptr26, len26, err26 := writeString(ctx, name24, memory26, realloc26)
	if err26 != nil {
		var default26 MobileLikelihood
		return default26, err26
	}
	i.module.Memory().WriteUint32Le(ptr0+104, uint32(len26))
	i.module.Memory().WriteUint32Le(ptr0+100, uint32(ptr26))
	memory27 := i.module.Memory()
	realloc27 := i.module.ExportedFunction("cabi_realloc")
	ptr27, len27, err27 := writeString(ctx, version24, memory27, realloc27)
	if err27 != nil {
		var default27 MobileLikelihood
		return default27, err27
	}
	i.module.Memory().WriteUint32Le(ptr0+112, uint32(len27))
	i.module.Memory().WriteUint32Le(ptr0+108, uint32(ptr27))
	memory28 := i.module.Memory()
	realloc28 := i.module.ExportedFunction("cabi_realloc")
	ptr28, len28, err28 := writeString(ctx, platform10, memory28, realloc28)
	if err28 != nil {
		var default28 MobileLikelihood
		return default28, err28
	}
	i.module.Memory().WriteUint32Le(ptr0+120, uint32(len28))
	i.module.Memory().WriteUint32Le(ptr0+116, uint32(ptr28))
	memory29 := i.module.Memory()
	realloc29 := i.module.ExportedFunction("cabi_realloc")
	ptr29, len29, err29 := writeString(ctx, orig10, memory29, realloc29)
	if err29 != nil {
		var default29 MobileLikelihood
		return default29, err29
	}
	i.module.Memory().WriteUint32Le(ptr0+128, uint32(len29))
	i.module.Memory().WriteUint32Le(ptr0+124, uint32(ptr29))
	if secChUa1 == nil {
		i.module.Memory().WriteByte(ptr0+132, 0)
	} else {
		variantPayload := *secChUa1
		i.module.Memory().WriteByte(ptr0+132, 1)
		versions30 := variantPayload.Versions
		mobile30 := variantPayload.Mobile
		platform30 := variantPayload.Platform
		arch30 := variantPayload.Arch
		bitness30 := variantPayload.Bitness
		vec34 := versions30
		len34 := uint64(len(vec34))
		result34, err34 := i.module.ExportedFunction("cabi_realloc").Call(ctx, 0, 0, 4, len34*16)
		if err34 != nil {
			var default34 MobileLikelihood
			return default34, err34
		}
		ptr34 := result34[0]
		for idx := uint64(0); idx < len34; idx++ {
			e := vec34[idx]
			base := uint32(ptr34 + uint64(idx)*uint64(16))
			name31 := e.Name
			version31 := e.Version
			memory32 := i.module.Memory()
			realloc32 := i.module.ExportedFunction("cabi_realloc")
			ptr32, len32, err32 := writeString(ctx, name31, memory32, realloc32)
			if err32 != nil {
				var default32 MobileLikelihood
				return default32, err32
			}
			i.module.Memory().WriteUint32Le(base+4, uint32(len32))
			i.module.Memory().WriteUint32Le(base+0, uint32(ptr32))
			memory33 := i.module.Memory()
			realloc33 := i.module.ExportedFunction("cabi_realloc")
			ptr33, len33, err33 := writeString(ctx, version31, memory33, realloc33)
			if err33 != nil {
				var default33 MobileLikelihood
				return default33, err33
			}
			i.module.Memory().WriteUint32Le(base+12, uint32(len33))
			i.module.Memory().WriteUint32Le(base+8, uint32(ptr33))
		}
		i.module.Memory().WriteUint32Le(ptr0+140, uint32(len34))
		i.module.Memory().WriteUint32Le(ptr0+136, uint32(ptr34))
		if mobile30 == nil {
			i.module.Memory().WriteByte(ptr0+144, 0)
		} else {
			variantPayload := *mobile30
			i.module.Memory().WriteByte(ptr0+144, 1)
			var value35 uint32
			if variantPayload {
				value35 = 1
			} else {
				value35 = 0
			}
			var byte36 uint8
			switch value35 {
			case 0:
				byte36 = 0
			case 1:
				byte36 = 1
			default:
				// TODO(#8): Return an error if the return type allows it
				panic(errors.New("invalid int8 value encountered"))
			}
			i.module.Memory().WriteByte(ptr0+145, byte36)
		}
		memory38 := i.module.Memory()
		realloc38 := i.module.ExportedFunction("cabi_realloc")
		ptr38, len38, err38 := writeString(ctx, platform30, memory38, realloc38)
		if err38 != nil {
			var default38 MobileLikelihood
			return default38, err38
		}
		i.module.Memory().WriteUint32Le(ptr0+152, uint32(len38))
		i.module.Memory().WriteUint32Le(ptr0+148, uint32(ptr38))
		memory39 := i.module.Memory()
		realloc39 := i.module.ExportedFunction("cabi_realloc")
		ptr39, len39, err39 := writeString(ctx, arch30, memory39, realloc39)
		if err39 != nil {
			var default39 MobileLikelihood
			return default39, err39
		}
		i.module.Memory().WriteUint32Le(ptr0+160, uint32(len39))
		i.module.Memory().WriteUint32Le(ptr0+156, uint32(ptr39))
		memory40 := i.module.Memory()
		realloc40 := i.module.ExportedFunction("cabi_realloc")
		ptr40, len40, err40 := writeString(ctx, bitness30, memory40, realloc40)
		if err40 != nil {
			var default40 MobileLikelihood
			return default40, err40
		}
		i.module.Memory().WriteUint32Le(ptr0+168, uint32(len40))
		i.module.Memory().WriteUint32Le(ptr0+164, uint32(ptr40))
	}
	raw42, err42 := i.module.ExportedFunction("is-mobile").Call(ctx, uint64(ptr0))
	if err42 != nil {
		var default42 MobileLikelihood
		return default42, err42
	}

	// The cleanup via `cabi_post_*` cleans up the memory in the guest. By
	// deferring this, we ensure that no memory is corrupted before the function
	// is done accessing it.
	defer func() {
		if postFn := i.module.ExportedFunction("cabi_post_is-mobile"); postFn != nil {
			if _, err := postFn.Call(ctx, raw42...); err != nil {
				// If we get an error during cleanup, something really bad is
				// going on, so we panic. Also, you can't return the error from
				// the `defer`
				panic(errors.New("failed to cleanup"))
			}
		}
	}()

	results42 := raw42[0]
	value43, ok43 := i.module.Memory().ReadByte(uint32(results42 + 0))
	if !ok43 {
		var default43 MobileLikelihood
		return default43, errors.New("failed to read byte from memory")
	}
	var value54 MobileLikelihood
	var err54 error
	switch value43 {
	case 0:
		value44, ok44 := i.module.Memory().ReadByte(uint32(results42 + 4))
		if !ok44 {
			var default44 MobileLikelihood
			return default44, errors.New("failed to read byte from memory")
		}
		value45 := value44 != 0
		value46, ok46 := i.module.Memory().ReadByte(uint32(results42 + 5))
		if !ok46 {
			var default46 MobileLikelihood
			return default46, errors.New("failed to read byte from memory")
		}
		value47 := value46 != 0
		value48, ok48 := i.module.Memory().ReadByte(uint32(results42 + 6))
		if !ok48 {
			var default48 MobileLikelihood
			return default48, errors.New("failed to read byte from memory")
		}
		value49 := value48 != 0
		value50 := MobileLikelihood{
			IsSlow:  value45,
			IsPhone: value47,
			IsBot:   value49,
		}
		value54 = value50
	case 1:
		ptr51, ok51 := i.module.Memory().ReadUint32Le(uint32(results42 + 4))
		if !ok51 {
			var default51 MobileLikelihood
			return default51, errors.New("failed to read pointer from memory")
		}
		len52, ok52 := i.module.Memory().ReadUint32Le(uint32(results42 + 8))
		if !ok52 {
			var default52 MobileLikelihood
			return default52, errors.New("failed to read length from memory")
		}
		buf53, ok53 := i.module.Memory().Read(ptr51, len52)
		if !ok53 {
			var default53 MobileLikelihood
			return default53, errors.New("failed to read bytes from memory")
		}
		str53 := string(buf53)
		err54 = errors.New(str53)
	default:
		err54 = errors.New("invalid variant discriminant for expected")
	}
	return value54, err54
}
